name: Publish Gem

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Release gem
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          gem build yt-dlp.rb.gemspec
          VERSION=$(ruby -e "puts Gem::Specification.load('yt-dlp.rb.gemspec').version")
          gem push yt-dlp.rb-${VERSION}.gem
          
